### ISSUE TITLE
How to infer on own data?

### ISSUE THREAD

**Issue by HeChengHui** [CVMI-Lab/CoDet#14]
@machuofan 
Thank you for your work!
wonder it is possible to provide an inference script to test on my own video/images?

**Comment by machuofan** [comment]
Hi, we have just added the [inference script](https://github.com/CVMI-Lab/CoDet/blob/0ec1c6d333ad9b1501db0a08b9808d80faf30326/demo.py), which is borrowed from [Detic](https://github.com/facebookresearch/Detic/tree/main).

You can now test with custom images/videos using
~~~
python demo.py --config-file [config_file] --input [your_image_file] --output [output_file_path] --vocabulary lvis --opts MODEL.WEIGHTS [model_weights]
~~~

Or you can customize the test vocabulary, e.g.,
~~~
python demo.py --config-file [config_file] --input [your_image_file] --output [output_file_path] --vocabulary custom --custom_vocabulary headphone,webcam,paper,coffe --confidence-threshold 0.3 --opts MODEL.WEIGHTS [model_weights]
~~~

**Comment by HeChengHui** [comment]
@machuofan 

```
Arguments: Namespace(config_file='/CoDet/configs/CoDet_OVLVIS_EVA_4x.yaml', webcam=None, cpu=False, video_input=None, input=['frame_367.jpg'], output='demo_output/out.jpg', vocabulary='custom', custom_vocabulary='cash,money,person', pred_all_class=False, confidence_threshold=0.3, opts=['MODEL.WEIGHTS', /CoDet/models/CoDet_OVLVIS_EVA_4x.pth'])
Loading pretrained CLIP
======== shape of rope freq torch.Size([1024, 64]) ========
======== shape of rope freq torch.Size([6400, 64]) ========
Traceback (most recent call last):
  File "CoDet/demo.py", line 141, in <module>
    demo = VisualizationDemo(cfg, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CoDet/codet/predictor.py", line 67, in __init__
    self.predictor = DefaultPredictor(cfg)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/engine/defaults.py", line 293, in __init__
    self.model = build_model(self.cfg)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CoDet/codet/modeling/meta_arch/custom_rcnn.py", line 69, in from_config
    ret = super().from_config(cfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 84, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CoDet/codet/modeling/roi_heads/codet_roi_heads.py", line 57, in from_config
    ret = super().from_config(cfg, input_shape)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/modeling/roi_heads/cascade_rcnn.py", line 96, in from_config
    ret = super().from_config(cfg, input_shape)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 610, in from_config
    ret.update(cls._init_box_head(cfg, input_shape))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CoDet/codet/modeling/roi_heads/codet_roi_heads.py", line 78, in _init_box_head
    CoDetFastRCNNOutputLayers(
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CoDet/codet/modeling/roi_heads/codet_fast_rcnn.py", line 178, in from_config
    ret['cls_score'] = ZeroShotClassifier(cfg, input_shape)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/detectron2/config/config.py", line 190, in wrapped
    init_func(self, **explicit_args)
  File "/CoDet/codet/modeling/roi_heads/zero_shot_classifier.py", line 70, in __init__
    assert self.detection_weight.shape[1] == num_classes + 1, self.detection_weight.shape
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ZeroShotClassifier' object has no attribute 'detection_weight'
```

**Comment by danielgf0824** [comment]
I meet some errors when using this infer demo with ZeroShotClassifier. Did you ever fix it? 

> @machuofan Thank you for your work! wonder it is possible to provide an inference script to test on my own video/images?

**Comment by machuofan** [comment]
This error relates to the 'rand' initialization mode of ZeroShotClassifier, you can fix it by adding the following code right after [line 65](https://github.com/CVMI-Lab/CoDet/blob/0ec1c6d333ad9b1501db0a08b9808d80faf30326/codet/modeling/roi_heads/zero_shot_classifier.py#L65).
```
self.detection_weight = nn.Parameter(detection_weight) 
```

Besides, the last two lines of function [reset_cls_test](https://github.com/CVMI-Lab/CoDet/blob/5e4de9170d8b87ceea1ea553583c6468fecfb5cf/codet/modeling/utils.py#L48) needs to be changed to
```
del model.module.roi_heads.box_predictor.cls_score.detection_weight
model.module.roi_heads.box_predictor.cls_score.detection_weight = zs_weight
```

**Comment by alejosierra** [comment]
Hi. I was trying to run the updated demo script but I run into this error:

`python demo.py --config-file configs/CoDet_OVLVIS_R5021k_4x_ft4x.yaml --input image.jpg --output out2.jpg --vocabulary custom --custom_vocabulary woman,boy,mother,angel,player,football --confidence-threshold 0.3 --opts MODEL.WEIGHTS chk_pts/CoDet_OVLVIS_R5021k_4x_ft4x.pth`

> WARNING [04/24 14:01:14 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.0.cls_score.zs_weight' to the model due to incompatible shapes: (512, 4707) in the checkpoint but (512, 1204) in the model! You might want to double check if this is expected.
WARNING [04/24 14:01:14 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.1.cls_score.zs_weight' to the model due to incompatible shapes: (512, 4707) in the checkpoint but (512, 1204) in the model! You might want to double check if this is expected.
WARNING [04/24 14:01:14 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.2.cls_score.zs_weight' to the model due to incompatible shapes: (512, 4707) in the checkpoint but (512, 1204) in the model! You might want to double check if this is expected.
WARNING [04/24 14:01:14 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
roi_heads.box_predictor.0.cls_score.zs_weight
roi_heads.box_predictor.1.cls_score.zs_weight
roi_heads.box_predictor.2.cls_score.zs_weight
Traceback (most recent call last):
  File "demo.py", line 140, in <module>
    demo = VisualizationDemo(cfg, args)
  File "/MY_DIR/codet/CoDet/codet/predictor.py", line 68, in __init__
    reset_cls_test(self.predictor.model, classifier, num_classes)
  File "/MY_DIR/codet/CoDet/codet/modeling/utils.py", line 33, in reset_cls_test
    model.module.roi_heads.num_classes = num_classes
  File "/Conda_DIR/envs/codet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CustomRCNN' object has no attribute 'module'

I made the following fix to the `def reset_cls_test(model, cls_path, num_classes):` function
```python
def reset_cls_test(model, cls_path, num_classes):
	model.roi_heads.num_classes = num_classes
    if type(cls_path) == str:
        print('Resetting zs_weight', cls_path)
        zs_weight = torch.tensor(
            np.load(cls_path),
            dtype=torch.float32).permute(1, 0).contiguous() # D x C
    else:
        zs_weight = cls_path
    zs_weight = torch.cat(
        [zs_weight, zs_weight.new_zeros((zs_weight.shape[0], 1))],
        dim=1) # D x (C + 1)
    for box_predictor in model.roi_heads.box_predictor:
        if box_predictor.cls_score.norm_weight:
            zs_weight = F.normalize(zs_weight, p=2, dim=0)
        zs_weight = zs_weight.to(model.device)
        # for k in range(len(model.roi_heads.box_predictor)):
        del box_predictor.cls_score.zs_weight
        box_predictor.cls_score.zs_weight = zs_weight
``` 
But then I run into a new problem:

>  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                                                                                                                                     | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 149, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/MY_DIR/codet/CoDet/codet/predictor.py", line 97, in run_on_image
    vis_output = visualizer.draw_instance_predictions(predictions=instances)
  File "/MY_DIR/codet/CoDet/third_party/detectron2/detectron2/utils/visualizer.py", line 398, in draw_instance_predictions
    labels = _create_text_labels(classes, scores, self.metadata.get("thing_classes", None))
  File "/MY_DIR/codet/CoDet/third_party/detectron2/detectron2/utils/visualizer.py", line 244, in _create_text_labels
    labels = [class_names[i] for i in classes]
  File "/MY_DIR/codet/CoDet/third_party/detectron2/detectron2/utils/visualizer.py", line 244, in <listcomp>
    labels = [class_names[i] for i in classes]
IndexError: list index out of range

I debugged the prediction and the predicted classes indices have big values >100, while I only have 6 classes.

Is there something I am doing wrong?

Thanks

**Comment by machuofan** [comment]
Hi, this error suggests the classifier head didn't adopt the correct set of text embeddings. It seems I made a mistake when updating the `reset_cls_test` function. What if you revert the changes on `reset_cls_test`?

**Comment by alejosierra** [comment]
With the version from the original commit `66552efc75f37c5360225e23e47f497506f2dee6` I get the exact same error:

> raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CustomRCNN' object has no attribute 'module'

In my fix I just removed the module attribute and iterated over the box_predictor elements, But it was more intuition, to avoid the error.

**Comment by machuofan** [comment]
Thanks for the feedback. I have fixed the bug and tested on my computer. Now it works well. You can have a try by pulling the latest commit.

**Comment by alejosierra** [comment]
Thank you. It works for me now :smiley:
